---
# linux_core/defaults/main.yml — Valores por defecto del role
# -----------------------------------------------------------------------------

# Nombres de interfaces por defecto (Se sobreescriben en el playbook de cada Core)
nic_trunk1: "ens34"
nic_acc: "ens35"
nic_int: "ens36"
nic_internet: "ens37"
nic_trunk2: "ens37"

# Ficheros de configuración del sistema
netplan_config_file: "/etc/netplan/50-cloud-init.yaml"
netplan_backup_file: "/etc/netplan/50-cloud-init.yaml.bak"

# Configuración FRR
frr_config_file: "/etc/frr/frr.conf"
frr_daemons_file: "/etc/frr/daemons"

# Configuración Keepalived
keepalived_config_file: "/etc/keepalived/keepalived.conf"
keepalived_auth_pass: "AN3IBL3P4SS"

# Parámetros OSPF
ospf_area: "0.0.0.0"

# Valores base de identidad (Se cambian dinámicamente)
core_id: "core_generic"
core_state: "BACKUP"
core_priority: 100
core_unicast_src_ip: "10.0.0.1"
core_unicast_peer_ip: "10.0.0.2"
core_router_id: "10.0.0.1"